import { LetterCategory } from './types';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'zh', name: '中文' },
  { code: 'de', name: 'Deutsch' },
  { code: 'es', name: 'Español' },
  { code: 'ja', name: '日本語' },
];

export const TRANSLATIONS: { [key: string]: { [key: string]: string } } = {
    en: {
        'login.title': 'Login to LetterOn',
        'login.slogan': 'Your intelligent letter assistant.',
        'login.email': 'Email',
        'login.password': 'Password',
        'login.button': 'Login',
        'login.register': "Don't have an account? Register",
        'register.title': 'Create an Account',
        'register.displayName': 'Display Name',
        'register.button': 'Register',
        'register.login': 'Already have an account? Login',
        'navbar.logout': 'Logout',
        'navbar.account': 'Account',
        'letters.title': 'My Letters',
        'letters.add': 'Add Letter',
        'letters.search': 'Search by keyword...',
        'letters.filter.category': 'Category',
        'letters.filter.allCategories': 'All Categories',
        'letters.filter.starred': 'Starred',
        'letters.filter.reminder': 'Has Reminder',
        'letter.sentOn': 'Sent on',
        'letter.uploadedOn': 'Uploaded on',
        'letter.status.none': 'None',
        'letter.status.wait_for_action': 'Action needed',
        'letter.status.complete': 'Complete',
        'letter.status.canceled': 'Canceled',
        'category.government': 'Government',
        'category.education': 'Education',
        'category.bank': 'Bank',
        'category.purchase': 'Purchase',
        'category.utility': 'Utility',
        'category.tax': 'Tax',
        'category.insurance': 'Insurance',
        'category.legal': 'Legal',
        'category.personal': 'Personal',
        'category.subscription': 'Subscription',
        'category.delivery': 'Delivery',
        'category.general': 'General',
        'category.other': 'Other',
        'detail.originalImages': 'Original Images',
        'detail.senderInfo': 'Sender Information',
        'detail.category': 'Category',
        'detail.note': 'My Note',
        'detail.addNote': 'Add a note...',
        'detail.analysis': 'AI Analysis',
        'detail.summary': 'Summary',
        'detail.originalContent': 'Original Content',
        'detail.showOriginalText': 'Show Original Text',
        'detail.showTranslatedOriginalText': 'Show Translated Original Text',
        'detail.keyInfo': 'Key Information',
        'detail.suggestion': 'Suggested Action',
        'detail.deadline': 'Action Deadline',
        'detail.translation': 'Translation',
        'detail.suggestionBanner': 'AI Suggestion',
        'detail.askAI': 'Ask AI about this letter',
        'detail.translateButton': 'Translate',
        'detail.backToList': '← Back to Letter list',
        'chat.title': 'Chat with AI',
        'chat.inputPlaceholder': 'Ask a question about the letter...',
        'addLetter.title': 'Add a New Letter',
        'addLetter.uploadImages': 'Upload letter images',
        'addLetter.uploadButton': 'Select Images',
        'addLetter.translation': 'Translate to (optional)',
        'addLetter.noTranslation': 'No Translation',
        'addLetter.submit': 'Analyze & Save',
        'addLetter.analyzing': 'Analyzing your letter with AI...',
        'addLetter.success': 'Letter Analyzed!',
        'addLetter.backToHome': 'Back to Home',
        'addLetter.viewDetails': 'View Details',
        'addLetter.error': 'Analysis failed. Please try again.',
        'confirm.delete.title': 'Delete Letter',
        'confirm.delete.message': 'Are you sure you want to delete this letter? This action cannot be undone.',
        'confirm.delete.confirm': 'Delete',
        'confirm.delete.cancel': 'Cancel',
        'reminder.title': 'Set a Reminder',
        'reminder.dateLabel': 'Reminder Date & Time',
        'reminder.setButton': 'Add reminder to Google Calendar',
    },
    de: {
        'login.title': 'Anmelden bei LetterOn',
        'login.slogan': 'Ihr intelligenter Briefassistent.',
        'login.email': 'E-Mail',
        'login.password': 'Passwort',
        'login.button': 'Anmelden',
        'login.register': 'Kein Konto? Registrieren',
        'register.title': 'Konto erstellen',
        'register.displayName': 'Anzeigename',
        'register.button': 'Registrieren',
        'register.login': 'Bereits ein Konto? Anmelden',
        'navbar.logout': 'Abmelden',
        'navbar.account': 'Konto',
        'letters.title': 'Meine Briefe',
        'letters.add': 'Brief hinzufügen',
        'letters.search': 'Suche nach Stichwort...',
        'letters.filter.category': 'Kategorie',
        'letters.filter.allCategories': 'Alle Kategorien',
        'letters.filter.starred': 'Markiert',
        'letters.filter.reminder': 'Mit Erinnerung',
        'letter.sentOn': 'Gesendet am',
        'letter.uploadedOn': 'Hochgeladen am',
        'letter.status.none': 'Keine',
        'letter.status.wait_for_action': 'Handlung erforderlich',
        'letter.status.complete': 'Abgeschlossen',
        'letter.status.canceled': 'Storniert',
        'category.government': 'Behörde',
        'category.education': 'Bildung',
        'category.bank': 'Bank',
        'category.purchase': 'Kauf',
        'category.utility': 'Versorger',
        'category.tax': 'Steuer',
        'category.insurance': 'Versicherung',
        'category.legal': 'Rechtliches',
        'category.personal': 'Persönlich',
        'category.subscription': 'Abonnement',
        'category.delivery': 'Lieferung',
        'category.general': 'Allgemein',
        'category.other': 'Andere',
        'detail.originalImages': 'Originalbilder',
        'detail.senderInfo': 'Absenderinformationen',
        'detail.category': 'Kategorie',
        'detail.note': 'Meine Notiz',
        'detail.addNote': 'Notiz hinzufügen...',
        'detail.analysis': 'KI-Analyse',
        'detail.summary': 'Zusammenfassung',
        'detail.originalContent': 'Originalinhalt',
        'detail.showOriginalText': 'Originaltext anzeigen',
        'detail.showTranslatedOriginalText': 'Übersetzten Originaltext anzeigen',
        'detail.keyInfo': 'Schlüsselinformationen',
        'detail.suggestion': 'Handlungsempfehlung',
        'detail.deadline': 'Frist',
        'detail.translation': 'Übersetzung',
        'detail.suggestionBanner': 'KI-Vorschlag',
        'detail.askAI': 'Fragen Sie die KI zu diesem Brief',
        'detail.translateButton': 'Übersetzen',
        'detail.backToList': '← Zurück zur Briefliste',
        'chat.title': 'Chat mit KI',
        'chat.inputPlaceholder': 'Stellen Sie eine Frage zum Brief...',
        'addLetter.title': 'Neuen Brief hinzufügen',
        'addLetter.uploadImages': 'Briefbilder hochladen',
        'addLetter.uploadButton': 'Bilder auswählen',
        'addLetter.translation': 'Übersetzen nach (optional)',
        'addLetter.noTranslation': 'Keine Übersetzung',
        'addLetter.submit': 'Analysieren & Speichern',
        'addLetter.analyzing': 'Ihr Brief wird mit KI analysiert...',
        'addLetter.success': 'Brief analysiert!',
        'addLetter.backToHome': 'Zurück zur Startseite',
        'addLetter.viewDetails': 'Details anzeigen',
        'addLetter.error': 'Analyse fehlgeschlagen. Bitte versuchen Sie es erneut.',
        'confirm.delete.title': 'Brief löschen',
        'confirm.delete.message': 'Möchten Sie diesen Brief wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
        'confirm.delete.confirm': 'Löschen',
        'confirm.delete.cancel': 'Abbrechen',
        'reminder.title': 'Erinnerung einstellen',
        'reminder.dateLabel': 'Erinnerungsdatum & -zeit',
        'reminder.setButton': 'Erinnerung zu Google Kalender hinzufügen',
    },
    zh: {
        'login.title': '登入 LetterOn',
        'login.slogan': '您的智能信件助手。',
        'login.email': '電子郵件',
        'login.password': '密碼',
        'login.button': '登入',
        'login.register': '沒有帳號？ 註冊',
        'register.title': '建立帳號',
        'register.displayName': '顯示名稱',
        'register.button': '註冊',
        'register.login': '已有帳號？ 登入',
        'navbar.logout': '登出',
        'navbar.account': '帳戶',
        'letters.title': '我的信件',
        'letters.add': '新增信件',
        'letters.search': '關鍵字搜尋...',
        'letters.filter.category': '類別',
        'letters.filter.allCategories': '所有類別',
        'letters.filter.starred': '已標星',
        'letters.filter.reminder': '有提醒',
        'letter.sentOn': '寄件日期',
        'letter.uploadedOn': '上傳日期',
        'letter.status.none': '無',
        'letter.status.wait_for_action': '需要處理',
        'letter.status.complete': '已完成',
        'letter.status.canceled': '已取消',
        'category.government': '政府',
        'category.education': '教育',
        'category.bank': '銀行',
        'category.purchase': '購物',
        'category.utility': '公共事業',
        'category.tax': '稅務',
        'category.insurance': '保險',
        'category.legal': '法律',
        'category.personal': '個人',
        'category.subscription': '訂閱',
        'category.delivery': '配送',
        'category.general': '一般',
        'category.other': '其他',
        'detail.originalImages': '原始圖片',
        'detail.senderInfo': '寄件人資訊',
        'detail.category': '類別',
        'detail.note': '我的筆記',
        'detail.addNote': '新增筆記...',
        'detail.analysis': 'AI 分析',
        'detail.summary': '摘要',
        'detail.originalContent': '原文內容',
        'detail.showOriginalText': '顯示原文',
        'detail.showTranslatedOriginalText': '顯示翻譯後的原文',
        'detail.keyInfo': '關鍵資訊',
        'detail.suggestion': '建議行動',
        'detail.deadline': '行動截止日期',
        'detail.translation': '翻譯',
        'detail.suggestionBanner': 'AI 建議',
        'detail.askAI': '詢問 AI 關於此信件',
        'detail.translateButton': '翻譯',
        'detail.backToList': '← 返回信件列表',
        'chat.title': '與 AI 聊天',
        'chat.inputPlaceholder': '詢問關於信件的問題...',
        'addLetter.title': '新增信件',
        'addLetter.uploadImages': '上傳信件圖片',
        'addLetter.uploadButton': '選擇圖片',
        'addLetter.translation': '翻譯成（可選）',
        'addLetter.noTranslation': '不翻譯',
        'addLetter.submit': '分析並儲存',
        'addLetter.analyzing': '正在用 AI 分析您的信件...',
        'addLetter.success': '信件分析完成！',
        'addLetter.backToHome': '返回首頁',
        'addLetter.viewDetails': '查看詳情',
        'addLetter.error': '分析失敗，請重試。',
        'confirm.delete.title': '刪除信件',
        'confirm.delete.message': '您確定要刪除這封信件嗎？此操作無法復原。',
        'confirm.delete.confirm': '刪除',
        'confirm.delete.cancel': '取消',
        'reminder.title': '設定提醒',
        'reminder.dateLabel': '提醒日期與時間',
        'reminder.setButton': '將提醒加入 Google 日曆',
    },
    es: {
        'login.title': 'Iniciar sesión en LetterOn',
        'login.slogan': 'Tu asistente de cartas inteligente.',
        'login.email': 'Correo electrónico',
        'login.password': 'Contraseña',
        'login.button': 'Iniciar sesión',
        'login.register': '¿No tienes una cuenta? Regístrate',
        'register.title': 'Crear una cuenta',
        'register.displayName': 'Nombre de usuario',
        'register.button': 'Registrarse',
        'register.login': '¿Ya tienes una cuenta? Inicia sesión',
        'navbar.logout': 'Cerrar sesión',
        'navbar.account': 'Cuenta',
        'letters.title': 'Mis cartas',
        'letters.add': 'Añadir carta',
        'letters.search': 'Buscar por palabra clave...',
        'letters.filter.category': 'Categoría',
        'letters.filter.allCategories': 'Todas las categorías',
        'letters.filter.starred': 'Destacadas',
        'letters.filter.reminder': 'Con recordatorio',
        'letter.sentOn': 'Enviado el',
        'letter.uploadedOn': 'Subido el',
        'letter.status.none': 'Ninguno',
        'letter.status.wait_for_action': 'Acción necesaria',
        'letter.status.complete': 'Completado',
        'letter.status.canceled': 'Cancelado',
        'category.government': 'Gobierno',
        'category.education': 'Educación',
        'category.bank': 'Banco',
        'category.purchase': 'Compra',
        'category.utility': 'Servicio público',
        'category.tax': 'Impuestos',
        'category.insurance': 'Seguro',
        'category.legal': 'Legal',
        'category.personal': 'Personal',
        'category.subscription': 'Suscripción',
        'category.delivery': 'Entrega',
        'category.general': 'General',
        'category.other': 'Otro',
        'detail.originalImages': 'Imágenes originales',
        'detail.senderInfo': 'Información del remitente',
        'detail.category': 'Categoría',
        'detail.note': 'Mi nota',
        'detail.addNote': 'Añadir una nota...',
        'detail.analysis': 'Análisis de IA',
        'detail.summary': 'Resumen',
        'detail.originalContent': 'Contenido original',
        'detail.showOriginalText': 'Mostrar texto original',
        'detail.showTranslatedOriginalText': 'Mostrar texto original traducido',
        'detail.keyInfo': 'Información clave',
        'detail.suggestion': 'Acción sugerida',
        'detail.deadline': 'Fecha límite de acción',
        'detail.translation': 'Traducción',
        'detail.suggestionBanner': 'Sugerencia de IA',
        'detail.askAI': 'Preguntar a la IA sobre esta carta',
        'detail.translateButton': 'Traducir',
        'detail.backToList': '← Volver a la lista de cartas',
        'chat.title': 'Chatear con IA',
        'chat.inputPlaceholder': 'Haz una pregunta sobre la carta...',
        'addLetter.title': 'Añadir nueva carta',
        'addLetter.uploadImages': 'Subir imágenes de la carta',
        'addLetter.uploadButton': 'Seleccionar imágenes',
        'addLetter.translation': 'Traducir a (opcional)',
        'addLetter.noTranslation': 'Sin traducción',
        'addLetter.submit': 'Analizar y guardar',
        'addLetter.analyzing': 'Analizando tu carta con IA...',
        'addLetter.success': '¡Carta analizada!',
        'addLetter.backToHome': 'Volver al inicio',
        'addLetter.viewDetails': 'Ver detalles',
        'addLetter.error': 'Análisis fallido. Por favor, inténtalo de nuevo.',
        'confirm.delete.title': 'Eliminar carta',
        'confirm.delete.message': '¿Estás seguro de que quieres eliminar esta carta? Esta acción no se puede deshacer.',
        'confirm.delete.confirm': 'Eliminar',
        'confirm.delete.cancel': 'Cancelar',
        'reminder.title': 'Establecer un recordatorio',
        'reminder.dateLabel': 'Fecha y hora del recordatorio',
        'reminder.setButton': 'Añadir recordatorio a Google Calendar',
    },
    ja: {
        'login.title': 'LetterOnにログイン',
        'login.slogan': 'あなたのインテリジェントな手紙アシスタント。',
        'login.email': 'メールアドレス',
        'login.password': 'パスワード',
        'login.button': 'ログイン',
        'login.register': 'アカウントをお持ちでないですか？ 新規登録',
        'register.title': 'アカウントを作成',
        'register.displayName': '表示名',
        'register.button': '登録',
        'register.login': 'すでにアカウントをお持ちですか？ ログイン',
        'navbar.logout': 'ログアウト',
        'navbar.account': 'アカウント',
        'letters.title': '私の手紙',
        'letters.add': '手紙を追加',
        'letters.search': 'キーワードで検索...',
        'letters.filter.category': 'カテゴリー',
        'letters.filter.allCategories': 'すべてのカテゴリー',
        'letters.filter.starred': 'スター付き',
        'letters.filter.reminder': 'リマインダーあり',
        'letter.sentOn': '送信日',
        'letter.uploadedOn': 'アップロード日',
        'letter.status.none': 'なし',
        'letter.status.wait_for_action': '対応が必要',
        'letter.status.complete': '完了',
        'letter.status.canceled': 'キャンセル',
        'category.government': '政府',
        'category.education': '教育',
        'category.bank': '銀行',
        'category.purchase': '購入',
        'category.utility': '公共料金',
        'category.tax': '税金',
        'category.insurance': '保険',
        'category.legal': '法律',
        'category.personal': '個人',
        'category.subscription': '購読',
        'category.delivery': '配達',
        'category.general': '一般',
        'category.other': 'その他',
        'detail.originalImages': '元の画像',
        'detail.senderInfo': '差出人情報',
        'detail.category': 'カテゴリー',
        'detail.note': '私のメモ',
        'detail.addNote': 'メモを追加...',
        'detail.analysis': 'AI分析',
        'detail.summary': '概要',
        'detail.originalContent': '原文',
        'detail.showOriginalText': '原文を表示',
        'detail.showTranslatedOriginalText': '翻訳された原文を表示',
        'detail.keyInfo': '重要な情報',
        'detail.suggestion': '推奨されるアクション',
        'detail.deadline': 'アクションの期限',
        'detail.translation': '翻訳',
        'detail.suggestionBanner': 'AIの提案',
        'detail.askAI': 'この手紙についてAIに質問する',
        'detail.translateButton': '翻訳',
        'detail.backToList': '← 手紙一覧に戻る',
        'chat.title': 'AIとチャット',
        'chat.inputPlaceholder': '手紙に関する質問を入力...',
        'addLetter.title': '新しい手紙を追加',
        'addLetter.uploadImages': '手紙の画像をアップロード',
        'addLetter.uploadButton': '画像を選択',
        'addLetter.translation': '翻訳先 (任意)',
        'addLetter.noTranslation': '翻訳しない',
        'addLetter.submit': '分析して保存',
        'addLetter.analyzing': 'AIで手紙を分析中...',
        'addLetter.success': '手紙の分析が完了しました！',
        'addLetter.backToHome': 'ホームに戻る',
        'addLetter.viewDetails': '詳細を見る',
        'addLetter.error': '分析に失敗しました。もう一度お試しください。',
        'confirm.delete.title': '手紙を削除',
        'confirm.delete.message': '本当にこの手紙を削除しますか？この操作は元に戻せません。',
        'confirm.delete.confirm': '削除',
        'confirm.delete.cancel': 'キャンセル',
        'reminder.title': 'リマインダーを設定',
        'reminder.dateLabel': 'リマインダーの日時',
        'reminder.setButton': 'リマインダーをGoogleカレンダーに追加',
    },
};

export const TOP_LANGUAGES = [
    { code: "en", name: "English" },
    { code: "zh", name: "Chinese" },
    { code: "es", name: "Spanish" },
    { code: "hi", name: "Hindi" },
    { code: "ar", name: "Arabic" },
    { code: "pt", name: "Portuguese" },
    { code: "bn", name: "Bengali" },
    { code: "ru", name: "Russian" },
    { code: "ja", name: "Japanese" },
    { code: "de", name: "German" },
    { code: "fr", name: "French" },
    //... add more
];

export const CATEGORY_OPTIONS = Object.values(LetterCategory);